### ISSUE TITLE
Feature request: parsedown options

### ISSUE THREAD

**Issue by phlppschrr** [rockettpw/textformatter-parsedownextraplugin#1]
It would be great if you could include a configuration option for `setBreaksEnabled(true)` and `setUrlsLinked(false)`  
See the examples here: https://github.com/erusev/parsedown/wiki/Tutorial:-Get-Started

**Comment by mikerockett** [comment]
Thanks for the suggestion – I'll look into it when I can, though please feel free to submit a PR in the case I can't find time.

**Comment by mikerockett** [comment]
Closing as the repo has been moved over to Gitlab. Refer: https://github.com/rockettpw/textformatter-parsedownextraplugin/pull/2#issuecomment-471149129
